name: IPA Uploader

on:
  repository_dispatch:
    types:
      - upload-ipa

jobs:
  upload-testflight:
    runs-on: macos-latest

    steps:
      - name: Set credentials
        run: |
          APPSTORE_CONNECT_ISSUER_ID=$(jq -r '.client_payload.APPSTORE_CONNECT_ISSUER_ID' $GITHUB_EVENT_PATH)
          APPSTORE_CONNECT_KEY_ID=$(jq -r '.client_payload.APPSTORE_CONNECT_KEY_ID' $GITHUB_EVENT_PATH)
          APPSTORE_CONNECT_PRIVATE_KEY=$(jq -r '.client_payload.APPSTORE_CONNECT_PRIVATE_KEY' $GITHUB_EVENT_PATH | base64 -d)
          echo "::add-mask::$APPSTORE_CONNECT_ISSUER_ID"
          echo "::add-mask::$APPSTORE_CONNECT_KEY_ID"
          echo "::add-mask::$APPSTORE_CONNECT_PRIVATE_KEY"
          echo APPSTORE_CONNECT_ISSUER_ID=$APPSTORE_CONNECT_ISSUER_ID >> $GITHUB_ENV
          echo APPSTORE_CONNECT_KEY_ID=$APPSTORE_CONNECT_KEY_ID >> $GITHUB_ENV
          echo APPSTORE_CONNECT_PRIVATE_KEY=$APPSTORE_CONNECT_PRIVATE_KEY >> $GITHUB_ENV

      - name: Download IPA file
        run: |
          curl -o app.ipa "${{ github.event.client_payload.IPA_FILE_URL }}"

      - name: Upload app to TestFlight
        id: upload-tf
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: app.ipa
          issuer-id: ${{ env.APPSTORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ env.APPSTORE_CONNECT_KEY_ID }}
          api-private-key: ${{ env.APPSTORE_CONNECT_PRIVATE_KEY }}
        continue-on-error: true

      - name: Check job exit code
        run: |
          if [ "${{ steps.upload-tf.outcome }}" == "failure" ]; then
            echo "Uploading process failed!"
          else
            echo "Uploading process success!"
          fi
